### ISSUE TITLE
Participants with the same name in the same room

### ISSUE THREAD

**Issue by jbarop** [Planning-Poker-Teams/planning-poker#24]
If 2 participants with the same name are in the same room, only one participant is visible in the interface.

**Comment by felixabele** [comment]
currently we don't use unique identifiers for users but their name. Changing this would require major refactoring (we could use the connection ID). But having duplicate names may be not optimal as well from UX perspective.

What do you think about bypassing this issue with a unique user-name validation before entering the room?
